# Generated by Django 5.0 on 2023-12-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='vocabulary_users',
        ),
    ]
